version: 2
jobs:
  build:  # required for runs that don't use workflows
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
        auth:
          username: caffeinepotent
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
          environment:
            PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:| sudo pip install virtualenv 
              virtualenv -p python3 venv
              source venv/bin/activate
              pip install -r requirements.txt
    